//! Vendored `confluent/*.proto` sources.
//!
//! These are the Confluent-specific schemas — `confluent/meta.proto` and
//! `confluent/type/decimal.proto` — that Confluent Schema Registry treats as
//! ambient ("known") dependencies, so clients don't upload them as references.
//! A compiler won't resolve
//! `import "confluent/type/decimal.proto"` on its own — this crate bundles the
//! sources so you can feed them to whatever compiler you use.
//!
//! Ships `.proto` **source text**, not generated Rust types.
//!
//! ```
//! for (import_path, source) in proto_src_confluent::FILES {
//!     // e.g. hand to a protox FileResolver, a prost-reflect pool, buf, …
//!     let _ = (import_path, source);
//! }
//! ```

#![forbid(unsafe_code)]
#![no_std]

// `FILES: &[(&str, &str)]` of (import path, source text), generated by build.rs
// from every `.proto` under `proto/`.
include!(concat!(env!("OUT_DIR"), "/files.rs"));
