//! Vendored `google/type/*.proto` sources (the complete folder).
//!
//! These are the common types from [googleapis] (`Date`, `Money`, `LatLng`,
//! `Decimal`, …) that Confluent Schema Registry treats as ambient
//! dependencies. They are **not** protobuf well-known types
//! (`google/protobuf/*`), so a compiler won't resolve
//! `import "google/type/date.proto"` on its own — this crate bundles the
//! sources so you can feed them to whatever compiler you use.
//!
//! Ships `.proto` **source text**, not generated Rust types.
//!
//! ```
//! for (import_path, source) in proto_src_google_type::FILES {
//!     // e.g. hand to a protox FileResolver, a prost-reflect pool, buf, …
//!     let _ = (import_path, source);
//! }
//! ```
//!
//! [googleapis]: https://github.com/googleapis/googleapis

#![forbid(unsafe_code)]
#![no_std]

// `FILES: &[(&str, &str)]` of (import path, source text), generated by build.rs
// from every `.proto` under `proto/`.
include!(concat!(env!("OUT_DIR"), "/files.rs"));
